import { HealthUnit, User } from "./types";

export const mockUsers: User[] = [
  { id: "u1", name: "Admin Sistema", email: "admin@mapssaude.com", role: "admin" },
  { id: "u2", name: "Hospital das Clínicas", email: "hc@mapssaude.com", role: "health_unit", unitId: "1" },
  { id: "u3", name: "Maria Silva", email: "maria@email.com", role: "user" },
  { id: "u4", name: "João Santos", email: "joao@email.com", role: "user" },
];

export const mockUnits: HealthUnit[] = [
  {
    id: "1",
    name: "Hospital Regional de Alagoinhas",
    category: "hospital",
    address: "Av. Antônio Carlos Magalhães, 500",
    neighborhood: "Centro",
    city: "Alagoinhas",
    state: "BA",
    zipCode: "48010-020",
    lat: -12.1370,
    lng: -38.4190,
    phone: "(75) 3422-1200",
    whatsapp: "(75) 99812-1200",
    email: "contato@hral.ba.gov.br",
    hours: "24 horas",
    specialties: ["Clínica Médica", "Cirurgia Geral", "Pediatria", "Ortopedia", "Ginecologia", "UTI"],
    professionals: [
      { id: "p1", name: "Dr. Carlos Brito", role: "doctor", specialty: "Clínica Médica", crm: "CRM-BA 12345" },
      { id: "p2", name: "Dra. Ana Ferreira", role: "doctor", specialty: "Pediatria", crm: "CRM-BA 23456" },
      { id: "p3", name: "Dr. José Oliveira", role: "doctor", specialty: "Ortopedia", crm: "CRM-BA 34567" },
    ],
    reviews: [
      { id: "r1", userId: "u3", userName: "Maria Silva", rating: 4, comment: "Bom atendimento, profissionais dedicados.", date: "2026-05-10", locationCorrect: true },
      { id: "r2", userId: "u4", userName: "João Santos", rating: 3, comment: "Demora no atendimento, mas equipe competente.", date: "2026-06-01", locationCorrect: true },
    ],
    rating: 3.8,
    totalReviews: 187,
    approved: true,
    locationVerified: true,
    locationVotes: 74,
  },
  {
    id: "2",
    name: "UPA 24h Alagoinhas",
    category: "upa",
    address: "Rua Lauro de Freitas, 280",
    neighborhood: "Novo Horizonte",
    city: "Alagoinhas",
    state: "BA",
    zipCode: "48035-180",
    lat: -12.1450,
    lng: -38.4310,
    phone: "(75) 3421-0800",
    hours: "24 horas",
    specialties: ["Pronto-Atendimento", "Emergência", "Pediatria", "Observação"],
    professionals: [
      { id: "p4", name: "Dra. Fernanda Lima", role: "doctor", specialty: "Medicina de Emergência", crm: "CRM-BA 45678" },
      { id: "p5", name: "Enf. Paulo Andrade", role: "nurse" },
    ],
    reviews: [
      { id: "r3", userId: "u3", userName: "Maria Silva", rating: 3, comment: "Atendimento razoável, espera longa nos finais de semana.", date: "2026-04-20", locationCorrect: true },
    ],
    rating: 3.5,
    totalReviews: 134,
    approved: true,
    locationVerified: true,
    locationVotes: 41,
  },
  {
    id: "3",
    name: "Farmácias Pague Menos - Centro",
    category: "pharmacy",
    address: "Rua Dr. José Moreira, 120",
    neighborhood: "Centro",
    city: "Alagoinhas",
    state: "BA",
    zipCode: "48010-010",
    lat: -12.1365,
    lng: -38.4255,
    phone: "(75) 3421-3300",
    whatsapp: "(75) 98877-3300",
    email: "alagoinhas@paguemenos.com.br",
    hours: "07:00 às 22:00",
    specialties: ["Medicamentos", "Genéricos", "Dermocosméticos", "Higiene"],
    professionals: [
      { id: "p6", name: "Farm. Beatriz Souza", role: "pharmacist", specialty: "Farmácia Clínica", crf: "CRF-BA 56789" },
    ],
    reviews: [
      { id: "r4", userId: "u4", userName: "João Santos", rating: 5, comment: "Sempre bem abastecida e atendimento rápido.", date: "2026-05-28", locationCorrect: true },
    ],
    rating: 4.5,
    totalReviews: 218,
    approved: true,
    locationVerified: true,
    locationVotes: 88,
  },
  {
    id: "4",
    name: "Clínica Saúde Integral",
    category: "clinic",
    address: "Av. Maria Quitéria, 740",
    neighborhood: "Maria Quitéria",
    city: "Alagoinhas",
    state: "BA",
    zipCode: "48030-250",
    lat: -12.1310,
    lng: -38.4160,
    phone: "(75) 3422-4500",
    whatsapp: "(75) 99654-4500",
    email: "contato@saudeintegral.com.br",
    hours: "Seg-Sex: 07:00-19:00 | Sáb: 07:00-13:00",
    specialties: ["Clínica Geral", "Ginecologia", "Dermatologia", "Nutrição", "Psicologia"],
    professionals: [
      { id: "p7", name: "Dra. Camila Borges", role: "doctor", specialty: "Ginecologia", crm: "CRM-BA 67890" },
      { id: "p8", name: "Dr. Ricardo Nunes", role: "doctor", specialty: "Dermatologia", crm: "CRM-BA 78901" },
    ],
    reviews: [
      { id: "r5", userId: "u3", userName: "Maria Silva", rating: 5, comment: "Clínica excelente, atendimento humanizado.", date: "2026-06-05", locationCorrect: true },
    ],
    rating: 4.6,
    totalReviews: 95,
    approved: true,
    locationVerified: true,
    locationVotes: 42,
  },
  {
    id: "5",
    name: "Laboratório Análises Clínicas Alagoinhas",
    category: "laboratory",
    address: "Rua Benjamin Constant, 350",
    neighborhood: "Centro",
    city: "Alagoinhas",
    state: "BA",
    zipCode: "48010-080",
    lat: -12.1395,
    lng: -38.4220,
    phone: "(75) 3422-6800",
    email: "lab@lacalagoinhas.com.br",
    hours: "Seg-Sex: 06:30-17:00 | Sáb: 06:30-12:00",
    specialties: ["Exames de Sangue", "Urina", "Fezes", "Microbiologia", "Hormônios"],
    professionals: [
      { id: "p9", name: "Dr. Eduardo Santos", role: "doctor", specialty: "Patologia Clínica", crm: "CRM-BA 89012" },
    ],
    reviews: [
      { id: "r6", userId: "u4", userName: "João Santos", rating: 5, comment: "Resultado entregue no prazo, coleta muito organizada.", date: "2026-06-10", locationCorrect: true },
    ],
    rating: 4.7,
    totalReviews: 312,
    approved: true,
    locationVerified: true,
    locationVotes: 121,
  },
  {
    id: "6",
    name: "Hospital e Maternidade Nossa Senhora do Amparo",
    category: "hospital",
    address: "Rua João Pessoa, 85",
    neighborhood: "Centro",
    city: "Alagoinhas",
    state: "BA",
    zipCode: "48010-050",
    lat: -12.1340,
    lng: -38.4200,
    phone: "(75) 3422-0500",
    email: "nossasenhora@hospitalamparo.com.br",
    hours: "24 horas",
    specialties: ["Maternidade", "Neonatologia", "Ginecologia", "Cirurgia Geral", "Pediatria"],
    professionals: [
      { id: "p10", name: "Dr. Henrique Alves", role: "doctor", specialty: "Obstetrícia", crm: "CRM-BA 90123" },
      { id: "p11", name: "Dra. Luísa Carneiro", role: "doctor", specialty: "Neonatologia", crm: "CRM-BA 01234" },
    ],
    reviews: [
      { id: "r7", userId: "u3", userName: "Maria Silva", rating: 4, comment: "Ótima maternidade, equipe muito atenciosa com as mães.", date: "2026-03-15", locationCorrect: true },
    ],
    rating: 4.3,
    totalReviews: 421,
    approved: true,
    locationVerified: true,
    locationVotes: 156,
  },
  {
    id: "7",
    name: "Drogaria São Paulo - Sto. Antônio",
    category: "pharmacy",
    address: "Av. Getúlio Vargas, 600",
    neighborhood: "Santo Antônio",
    city: "Alagoinhas",
    state: "BA",
    zipCode: "48025-000",
    lat: -12.1420,
    lng: -38.4270,
    phone: "(75) 3421-5500",
    hours: "07:00 às 21:00",
    specialties: ["Medicamentos", "Genéricos", "Perfumaria", "Vacinas"],
    professionals: [
      { id: "p12", name: "Farm. Lucas Barreto", role: "pharmacist", crf: "CRF-BA 12398" },
    ],
    reviews: [],
    rating: 4.0,
    totalReviews: 54,
    approved: true,
    locationVerified: false,
    locationVotes: 9,
  },
  {
    id: "8",
    name: "Clínica Popular Bem-Estar",
    category: "clinic",
    address: "Rua Themístocles Baleeiro, 190",
    neighborhood: "Brasília",
    city: "Alagoinhas",
    state: "BA",
    zipCode: "48040-000",
    lat: -12.1480,
    lng: -38.4150,
    phone: "(75) 3422-8800",
    whatsapp: "(75) 99543-8800",
    hours: "Seg-Sex: 07:00-21:00 | Sáb-Dom: 08:00-17:00",
    specialties: ["Clínica Geral", "Pediatria", "Cardiologia", "Ortopedia"],
    professionals: [
      { id: "p13", name: "Dr. André Costa", role: "doctor", specialty: "Clínica Geral", crm: "CRM-BA 13579" },
    ],
    reviews: [
      { id: "r8", userId: "u4", userName: "João Santos", rating: 4, comment: "Preço acessível e atendimento sem demora.", date: "2026-05-22" },
    ],
    rating: 4.1,
    totalReviews: 98,
    approved: true,
    locationVerified: true,
    locationVotes: 23,
  },
  {
    id: "9",
    name: "UPA Alagoinhas Norte",
    category: "upa",
    address: "Rua Cel. Virgílio Leite, 45",
    neighborhood: "Canaã",
    city: "Alagoinhas",
    state: "BA",
    zipCode: "48050-000",
    lat: -12.1280,
    lng: -38.4320,
    phone: "(75) 3421-9200",
    hours: "24 horas",
    specialties: ["Pronto-Atendimento", "Emergência", "Sutura", "Hidratação"],
    professionals: [
      { id: "p14", name: "Dra. Simone Nascimento", role: "doctor", specialty: "Medicina de Urgência", crm: "CRM-BA 24680" },
    ],
    reviews: [],
    rating: 3.6,
    totalReviews: 76,
    approved: true,
    locationVerified: true,
    locationVotes: 18,
  },
  {
    id: "10",
    name: "Labclin - Laboratório de Análises",
    category: "laboratory",
    address: "Av. Nações Unidas, 1200",
    neighborhood: "Cascalheira",
    city: "Alagoinhas",
    state: "BA",
    zipCode: "48045-000",
    lat: -12.1500,
    lng: -38.4100,
    phone: "(75) 3421-7700",
    email: "labclin@labclin.com.br",
    hours: "Seg-Sex: 06:30-17:30 | Sáb: 07:00-11:00",
    specialties: ["Análises Clínicas", "Bioquímica", "Imunologia", "Parasitologia"],
    professionals: [],
    reviews: [
      { id: "r9", userId: "u3", userName: "Maria Silva", rating: 4, comment: "Coleta rápida e resultado entregue por WhatsApp.", date: "2026-06-08", locationCorrect: true },
    ],
    rating: 4.2,
    totalReviews: 143,
    approved: true,
    locationVerified: true,
    locationVotes: 47,
  },
];

export const categoryLabels: Record<string, string> = {
  hospital: "Hospital",
  clinic: "Clínica",
  pharmacy: "Farmácia/Drogaria",
  upa: "UPA",
  laboratory: "Laboratório",
  all: "Todas",
};

export const categoryColors: Record<string, string> = {
  hospital: "#ef4444",
  clinic: "#3b82f6",
  pharmacy: "#22c55e",
  upa: "#f97316",
  laboratory: "#a855f7",
};

export const categoryIcons: Record<string, string> = {
  hospital: "🏥",
  clinic: "🩺",
  pharmacy: "💊",
  upa: "🚨",
  laboratory: "🔬",
};

export function calculateDistance(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLng / 2) *
      Math.sin(dLng / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}
